@startuml "oaCenter-Components"

[oaCenter-backend] as backend
[oaCenter-front] as front

'[swagger-ui-board] as sui  -->  dropped / legacy

package oacenter-integration-support {
    [oacenter-maven-plugin] as mvn
    [oacenter-gradle-plugin] as grd
    control "oacenter-java-client" as jv
}

database db

backend -- db : <JPA>
front .. backend : <REST>
sui .. backend : <REST>
grd -- jv
mvn -- jv
jv .. backend  : <REST>


@enduml